export const staticData = [
  { option: '0', style: { backgroundColor: 'green', textColor: '#fff' } },
  { option: '1', style: { backgroundColor: '#6A5ACD', textColor: '#fff' } },
  { option: '2', style: { backgroundColor: '#00FA9A', textColor: '#fff' }  },
  { option: '3', style: { backgroundColor: '#BDB76B', textColor: '#fff' }  },
  { option: '4', style: { backgroundColor: '#DC143C', textColor: '#fff' }  },
  { option: '5', style: { backgroundColor: '#4f820d', textColor: '#fff' }  },
  { option: '6', style: { backgroundColor: '	#DAA520', textColor: '#fff' }  },
  { option: '7', style: { backgroundColor: '#820d5f', textColor: '#fff' }  },
  { option: '8', style: { backgroundColor: '#2b2478', textColor: '#fff' }  },
  { option: '0' , style: { backgroundColor: '#9370DB', textColor: '#fff' } },
  { option: '10', style: { backgroundColor: '#ada41f', textColor: '#fff' }  },
  { option: '11', style: { backgroundColor: 'green', textColor: '#fff' } },
  { option: '12', style: { backgroundColor: '#6A5ACD', textColor: '#fff' } },
  { option: '13', style: { backgroundColor: '#00FA9A', textColor: '#fff' }  },
  { option: '14', style: { backgroundColor: '#BDB76B', textColor: '#fff' }  },
  { option: '15', style: { backgroundColor: '#DC143C', textColor: '#fff' }  },
  { option: '0', style: { backgroundColor: '#4f820d', textColor: '#fff' }  },
  { option: '17', style: { backgroundColor: '	#DAA520', textColor: '#fff' }  },
  { option: '18', style: { backgroundColor: '#820d5f', textColor: '#fff' }  },
  { option: '19', style: { backgroundColor: '#2b2478', textColor: '#fff' }  },
  { option: '20' , style: { backgroundColor: '#9370DB', textColor: '#fff' } },
  { option: '21', style: { backgroundColor: '#ada41f', textColor: '#fff' }  },
  { option: '22', style: { backgroundColor: '#820d5f', textColor: '#fff' }  },
  { option: '23', style: { backgroundColor: '#2b2478', textColor: '#fff' }  },
  { option: '24' , style: { backgroundColor: '#9370DB', textColor: '#fff' } },
  { option: '25', style: { backgroundColor: '#ada41f', textColor: '#fff' }  },
]